{% set name = "pyphen" %}
{% set version = "0.9.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Pyphen-{{ version }}.tar.gz
  sha256: 3b633a50873156d777e1f1075ba4d8e96a6ad0a3ca42aa3ea9a6259f93f18921

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6

test:
  imports:
    - pyphen
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pyphen.org/
  license: GPL-2.0-or-later, LGPL-2.1-or-later, MPL-1.1
  license_file: COPYING, COPYING.GPL, COPYING.LGPL, COPYING.MPL
  summary: Pure Python module to hyphenate text
  description: |
    Pyphen is a pure Python module to hyphenate text using existing Hunspell
    hyphenation dictionaries.
  doc_url: http://pyphen.org/
  dev_url: https://github.com/Kozea/Pyphen

extra:
  recipe-maintainers:
    - rmax
    - thewchan
