{% set name = "pyphen" %}

{% set version = "0.11.0" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2c3ed82c3a04317df5102addafe89652b0876bc6c6265f5dd4c3efaf02315e8


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit
    - pip
    - python >=3.6

  run:
    - python >=3.6

test:
  imports:
    - pyphen
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pyphen.org/
  license: GPL-2.0-or-later AND LGPL-2.1-or-later AND MPL-1.1
  license_file:
    - LICENSE
    - COPYING.GPL
    - COPYING.LGPL
    - COPYING.MPL
  summary: Pure Python module to hyphenate text
  description: |
    Pyphen is a pure Python module to hyphenate text using existing Hunspell
    hyphenation dictionaries.
  doc_url: http://pyphen.org/
  dev_url: https://github.com/Kozea/Pyphen

extra:
  recipe-maintainers:
    - rmax
    - thewchan
