travis:
  secure:
    BINSTAR_TOKEN: KvNwfDn0xG6CSVBS/R4oVTGJrGjMiDO2KMHJ9LzPX9OCL/oeuSLdWyw2k9nTAyTU8eOvp2lJBdJMwRzhkflMo+3CGlFcgQhf1knsfXDfO/7Kxyiux7mk9I5yMj6PIy3QHvncGjfRqENYJBU4+U9BmgqZLktzEHE6om4cHN7OK7TYlmmxMJR9owWb5E4fWeni+baPWAOVx3BJUWripDFkG6bS4FzTQacvQ8BI+bQzx75yo1glHSnAXX9y3PIhjlyLTZ7HbgBXnM7QlMZtxXh5R8IsiDRd4wIt6j407c9Mxhuy2r3ykzaPaHwpoHebBPuMQvCCy7hDD9NBlJJIiKUnkQ6CBym9ftJ9xsNNj84Qeya3zczStkdy4EdyiEgpDqZgNGNRn2g8BjX0aMFjlxSmy0a33ZK/dNkzJC/ES88qodvTWJMa2+SAuVgzulVS6PSwzw48iQgGZx7G8eoA7B6M6hns/aBPO30eFV83AdKPpkT5sUoKbXph35L6gwpMp0DopxbmItvdS1hJE/UGza2UGcRqVU5+JEycmUlXin2m7D7QpY4oJGwbrNJFpFle5mwIMED0DeL7JNyZaE7Ipsxgil0nKfU5TRoWrSpk3lhn2qQTQi0ljxjNu9e7ikMJh9tOEISxyRX2XuOggi4/2cmEFgic7yb+G8lc5XVFASRD7+k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
