travis:
  secure:
    BINSTAR_TOKEN: UAywxbi6tgTizhCcCcNL7YtvxzWPbz7iIBv9NKVMiiM4siHe/wCiYXEfY8POjdfAo1TeyrIuLQ6PHxwL8OdRRwrZ0S9faGo2JqvpTkDu4f2ttD4cPD4MlrNIwXrAGS6iRM2j0DIR6pEAklZIYQgcpvA2De4o9sZ8pvpO9v36NDuVOlKwE8yRm314B4PcuEv8J434Z4hCMxe0p6wLeUaehvDYM7amEaCThponDnopUF5ZuLcv5KS9wmc2DIJPnQU/TUZEXV1tyZg+J8reIPt0zw9krNBOCfxbp6aLL8qqevvrIOc4vRUfp9gQ3ogwPMznSeil7ebOig0EluRdoZKkwqHR/udwf5LMfHGdIZvdaLLgULeehUGXTIgmxmibFh9IADQfi+tLlV9DzD6Htq6A9cPToDHmkVmn6s1ujN9N2bx0Zc1DkXHu+cJxBflH935305kPkco3zTsw9vkZUzVpEheqYdzOFa+Ol/v0wJkDgm3X5LX+OA8blwJbzuj43yFUD4WDAxZDkSjhR5+ZqtdDQYhYcbSrzNnaqPMTTc3gNzXtACYhyPYSZ3uKJR4C+UXvFoMd+85wJ+XL1DWp7VbvJNq/91G4FW468wruKcNqPtGb/gVfdIenOE+7R1h3RvMrEG5PCWTKKG2cdVwr8xjjlq3hSgHQeU+sVvY+69ZsIu4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
